# Generated by Django 5.1.3 on 2024-12-05 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0003_rename_agent_name_subtask_agent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niuma',
            fields=[
                ('niuma_id', models.AutoField(primary_key=True, serialize=False)),
                ('niuma_name', models.CharField(max_length=100)),
                ('agent_type', models.CharField(max_length=100)),
                ('progress', models.FloatField(default=0.0)),
                ('subtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.subtask')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.user')),
            ],
        ),
    ]
