# Generated by Django 5.1.3 on 2024-11-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("isFinished", models.BooleanField(default=False)),
                ("allSubtasksLazied", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subtask",
            fields=[
                ("subtask_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("agent_name", models.CharField(max_length=100)),
                ("isLazied", models.BooleanField(default=False)),
                ("result", models.TextField()),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.task"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="team.user"
            ),
        ),
    ]
