# Generated by Django 5.1.3 on 2024-12-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='agent_name',
            new_name='agent_type',
        ),
    ]
