# Generated by Django 5.1.3 on 2024-11-28 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_rename_task_id_subtask_task_rename_user_id_task_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtask",
            old_name="isLazied",
            new_name="is_lazied",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="allSubtasksLazied",
            new_name="all_subtasks_lazied",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="isFinished",
            new_name="is_finished",
        ),
    ]
