"""
Django settings for LazyAI project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab  # 添加这行导入

# ... 其他导入和配置 ...

CELERY_BEAT_SCHEDULE = {
    'process-task-queues': {
        'task': 'team.taskspool_priority.TaskPool.periodic_schedule',
        'schedule': crontab(minute='*/1'),  # 每分钟执行一次
        'options': {
            'queue': 'celery',
            'expires': 55
        }
    }
}
# import environ

# env = environ.Env()
# environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n9pbuyx#btn4n216p((1m)kxw*4bnt0w&j309f#40q$0n-5q^4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'team.apps.TeamConfig',   # 添加后缀
    'niuma.apps.NiumaConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LazyAI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LazyAI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# postgresql://postgres.eraslmtrxqzkjsdrsnjh:[YOUR-PASSWORD]@aws-0-us-west-1.pooler.supabase.com:6543/postgres
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.eraslmtrxqzkjsdrsnjh',
        'PASSWORD': 'Triody@Lazy',
        'HOST': 'aws-0-us-west-1.pooler.supabase.com',
        'PORT': '6543',
        'OPTIONS': {
            'options': '-c search_path=public, auth',
        },
    }
}

import sys
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'test_db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SUPABASE_URL = env('SUPABASE_URL')
# SUPABASE_KEY = env('SUPABASE_KEY')

SUPABASE_URL="https://eraslmtrxqzkjsdrsnjh.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYXNsbXRyeHF6a2pzZHJzbmpoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMzI3OTc2MiwiZXhwIjoyMDQ4ODU1NzYyfQ.jmYb6INqZ331sItH-89EWK3YAZ_OfTGKYedtygYTov4"


# Celery配置
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'  # 设置时区
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


# # 队列设置
# CELERY_QUEUES = {
#     'ready_tasks': {
#         'exchange': 'ready_tasks',
#         'exchange_type': 'direct',
#         'routing_key': 'ready_tasks'
#     },
#     'waiting_tasks': {
#         'exchange': 'waiting_tasks',
#         'exchange_type': 'direct',
#         'routing_key': 'waiting_tasks'
#     }
# }

# # 任务路由
# CELERY_ROUTES = {
#     'team.taskspool.TaskPool.schedule': {'queue': 'ready_tasks'},
#     'team.taskspool.TaskPool.wait': {'queue': 'waiting_tasks'},
# }


# 启用优先级支持
CELERY_ENABLE_UTC = True
CELERY_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1  # 重要：确保高优先级任务能够被及时处理

# 队列设置
CELERY_QUEUES = {
    'high_priority': {
        'exchange': 'high_priority',
        'exchange_type': 'direct',
        'routing_key': 'high_priority',
        'queue_arguments': {'x-max-priority': 10}
    },
    'normal_priority': {
        'exchange': 'normal_priority',
        'exchange_type': 'direct',
        'routing_key': 'normal_priority',
        'queue_arguments': {'x-max-priority': 10}
    },
    'low_priority': {
        'exchange': 'low_priority',
        'exchange_type': 'direct',
        'routing_key': 'low_priority',
        'queue_arguments': {'x-max-priority': 10}
    },
    'waiting_tasks': {
        'exchange': 'waiting_tasks',
        'exchange_type': 'direct',
        'routing_key': 'waiting_tasks'
    }
}

# 路由配置
CELERY_TASK_ROUTES = {
    # 'team.tasks.add_team': {'queue': 'default'},
    'team.tasks.periodic_schedule': {'queue': 'celery'},  # 建议添加：明确指定 periodic_schedule 的队列
    # 'team.tasks.wait': {'queue': 'waiting_tasks'}  # 建议添加：明确指定 wait 任务的队列
}

# # Celery Worker 配置
# CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 控制 worker 预取任务数量
# CELERY_WORKER_MAX_TASKS_PER_CHILD = 100  # 每个 worker 进程最多处理的任务数
# CELERY_WORKER_CONCURRENCY = 4  # worker 进程数

# Celery Beat 配置
CELERY_BEAT_SCHEDULE = {
    'process-task-queues': {
        'task': 'team.tasks.periodic_schedule',
        'schedule': crontab(minute='*/1'),  # 每分钟执行一次
        'options': {'queue': 'celery'},  # Beat任务使用默认队列
    },
}
